#!/bin/sh

gsettings set org.gnome.desktop.wm.preferences auto-raise 'true'


"$HOME/ GazePlay-AFSR 1.9.7/lib/jre/bin/java" -cp "$HOME/ GazePlay-AFSR 1.9.7/lib/*" -Djdk.gtk.version=2 net.gazeplay.GazePlayLauncher --user "$HOME"


exit
