#!/bin/sh

gsettings set org.gnome.desktop.wm.preferences auto-raise 'true'

fuser -k 8081/tcp

if [ -d ~/.cache/google-chrome/Default ]; then
	rm -r ~/.cache/google-chrome/Default
fi

INTERAACTIONSCENE_DIRECTORY=$(ls $HOME/dist | grep "InterAACtionScene" | head -n 1)
if [ ! "$INTERAACTIONSCENE_DIRECTORY" = "" ]; then
  INTERAACTIONSCENE_PATH="$HOME/dist/${INTERAACTIONSCENE_DIRECTORY}"
  if [ -d "$INTERAACTIONSCENE_PATH" ]; then
    cd "$INTERAACTIONSCENE_PATH" || exit
    python3 -m http.server 8081 >InterAACtionScene.log &
  fi
fi

google-chrome --kiosk --fullscreen --disabled-component-update "http://localhost:8081/#/fr/connect/$USERNAME" &

echo "open http://localhost:8080/#/fr/connect/$USERNAME"

sh ~/interaactionBox_Interface-linux/bin/scripts/close_chrome.sh

exit
