#!/bin/sh

gsettings set org.gnome.desktop.wm.preferences auto-raise 'true'

fuser -k 8080/tcp
fuser -k 8081/tcp
fuser -k 8082/tcp
rm -r ~/.cache/google-chrome/Default/*

AUGCOM_DIRECTORY=$(ls ~/dist | grep "AugCom" | head -n 1)
AUGCOM_PATH="$HOME/dist/${AUGCOM_DIRECTORY}"
if [ -d "$AUGCOM_PATH" ]; then
    cd $AUGCOM_PATH || exit
    python3 -m http.server 8080 > AugCom.log &
fi

INTERAACTIONSCENE_DIRECTORY=$(ls ~/dist | grep "InterAACtionScene" | head -n 1)
INTERAACTIONSCENE_PATH="$HOME/dist/${INTERAACTIONSCENE_DIRECTORY}"
if [ -d "$INTERAACTIONSCENE_PATH" ]; then
    cd $INTERAACTIONSCENE_PATH || exit
    python3 -m http.server 8081 > InterAACtionScene.log &
fi

INTERAACTIONPLAYER_DIRECTORY=$(ls ~/dist | grep "InterAACtionPlayer" | head -n 1)
INTERAACTIONPLAYER_PATH="$HOME/dist/${INTERAACTIONPLAYER_DIRECTORY}"
if [ -d "$INTERAACTIONPLAYER_PATH" ]; then
    cd $INTERAACTIONPLAYER_PATH || exit
    python3 -m http.server 8082 > InterAACtionPlayer.log &
fi

cd ~/interaactionBox_Interface-linux/bin || exit
sh ./interaactionBoxOS-linux.sh
